import type { Metadata } from "next";
import { DM_Sans} from "next/font/google";
import "./globals.scss";
import Providers from "@/components/Providers";
import { UserModal } from "@/components/Modals/UserModal";

const poppins = DM_Sans({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        <Providers>
          <main>{children}</main>
          <UserModal />
        </Providers>
      </body>
    </html>
  );
}
